### ISSUE TITLE
Can more than one selection feature be added?

### ISSUE THREAD

**Issue by ahmetozalp** [phatnguyenuit/multiple-level-selection#2]

**Comment by phatnguyenuit** [comment]
Could describe more details about this one ?

**Comment by ahmetozalp** [comment]
multiple selection options in the last part.  I developed it with a simple code script, but when I press on it and want to remove the selected one, it resets and it doesn't work properly what I did.

**NOT: This feature is only required to be optional.**

example
<img width="588" alt="Ekran Resmi 2022-05-03 13 22 59" src="https://user-images.githubusercontent.com/7665820/166437846-8f082a32-1703-48af-ba6f-e2f8481b84b4.png">

https://codesandbox.io/s/multiple-level-selection-forked-jd83hb
_<-- I think it's a bit of a bad code can you take a look :)_



Video: https://www.youtube.com/watch?v=U8jItMubY9o&ab_channel=AhmetOZALP

As seen in the video, when I want to delete one of them, it is deleted. There is no problem, but the selector does not work properly.
